### ISSUE TITLE
AttributeError: 'BaseQuery' object has no attribute 'search'

### ISSUE THREAD

**Issue by alochym01** [blakev/Flask-WhooshAlchemy3#1]
hi
i testing this extension but get error
my config for Flask

> <Config {'DEBUG': True, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(31), 'USE_X_SENDFILE': False, 'LOGGER_NAME': 'test', 'LOGGER_HANDLER_POLICY': 'always', 'SERVER_NAME': None, 'APPLICATION_ROOT': None, 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(0, 43200), 'TRAP_BAD_REQUEST_ERRORS': False, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': True, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'BASEDIR': '/mnt/website/WORKING/website_crawler/config', 'SQLALCHEMY_DATABASE_URI': 'sqlite:////mnt/website/WORKING/website_crawler/config/app.db', 'SQLALCHEMY_TRACK_MODIFICATIONS': False, 'TOP_LEVEL_DIR': '/mnt/website/WORKING/website_crawler/config', 'WHOOSH_BASE': '/mnt/website/WORKING/website_crawler/config/packtpub', 'WHOOSH_INDEX_PATH': '/mnt/website/WORKING/website_crawler/config/packtpub', 'SQLALCHEMY_BINDS': None, 'SQLALCHEMY_NATIVE_UNICODE': None, 'SQLALCHEMY_ECHO': False, 'SQLALCHEMY_RECORD_QUERIES': None, 'SQLALCHEMY_POOL_SIZE': None, 'SQLALCHEMY_POOL_TIMEOUT': None, 'SQLALCHEMY_POOL_RECYCLE': None, 'SQLALCHEMY_MAX_OVERFLOW': None, 'SQLALCHEMY_COMMIT_ON_TEARDOWN': False}>

and my main.py

```
from flask import Flask, request
from flask_sqlalchemy import SQLAlchemy
import flask_whooshalchemy
from whoosh.analysis import StemmingAnalyzer
app = Flask(__name__)
app.config.from_pyfile('settings.py')
db = SQLAlchemy(app)
class PACKTPUB(db.Model):
    __tablename__ = "packtpubs"
    # these fields will be indexed by whoosh
    __searchable__ = ['title', 'isbn']
    _analyzer__ = StemmingAnalyzer()
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500))
    isbn = db.Column(db.String(50), index=True, unique=True)
    def __init__(self, title, isbn):
        self.title = title
        self.isbn = isbn
    def __repr__(self):
        return '<PacktPub Title %r>' % (self.title)
@app.route('/packtpubs/search')
def search():
    num_posts = min(request.args.get('limit', 10), 50)
    query = request.args.get('q', '')
    results = PACKTPUB.query.search(query, limit=num_posts)
    return results
@app.route('/packtpubs/create', methods=['POST'])
def packtpubs_create():
    packtpub = PACKTPUB(
        title=request.get_json().get('title'),
        isbn=request.get_json().get('isbn')
    )
    db.session.add(packtpub)
    db.session.commit()
    return 'DONE'
if __name__ == "__main__":
    app.run()
```

how to make it works

**Comment by blakev** [comment]
Cannot duplicate.

Try instantiating your database tables and fixing the `request` args portions.

```python
@app.route('/packtpubs/search')
def search():
    num_posts = 10
    query = request.args.get('q', '')
    results = PACKTPUB.query.search(query, limit=num_posts)
    return results  # <-- this won't work because you can't marshal SQLAlchemy models


@app.route('/packtpubs/create', methods=['POST'])
def packtpubs_create():
    j = request.get_json()

    packtpub = PACKTPUB(
        title=request.get_json().get('title'),
        isbn=request.get_json().get('isbn')
    )
    db.session.add(packtpub)
    db.session.commit()
    return 'DONE'


@app.before_first_request
def bootstrap():
    db.create_all()  # <- create the necessary table


if __name__ == "__main__":
    db.init_app(app)  # <- lazy bind the database to the app
    app.run()
```
Instead of returning results, I printed them out:

```python
>>> query
abc
>>> list(results)
[<PacktPub Title 'abc'>, <PacktPub Title 'abc zyx'>]
```

**Comment by alochym01** [comment]
i am still get error
```
    results = PACKTPUB.query.search(query, limit=num_posts)
AttributeError: 'BaseQuery' object has no attribute 'search
```
i use python
```
Python 3.6.2 (default, Jul 18 2017, 22:59:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux

```
my database

```
sqlite> .schema
CREATE TABLE packtpubs (
	id INTEGER NOT NULL, 
	title VARCHAR(500), 
	isbn VARCHAR(50), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_packtpubs_isbn ON packtpubs (isbn);
sqlite> select * from packtpubs
   ...> ;
   id = 1
title = abc
 isbn = 12346789
sqlite> 

```


```
from flask import Flask, request
from flask_sqlalchemy import SQLAlchemy
import flask_whooshalchemy
from whoosh.analysis import StemmingAnalyzer

app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy()


class PACKTPUB(db.Model):
    __tablename__ = "packtpubs"
    __searchable__ = ['title', 'content', 'summary']  # indexed fields
    __analyzer__ = StemmingAnalyzer()
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500))
    isbn = db.Column(db.String(50), index=True, unique=True)

    def __init__(self, title, isbn):
        self.title = title
        self.isbn = isbn

    def __repr__(self):
        return '<PacktPub Title %r>' % (self.title)


@app.route('/packtpubs/search')
def search():
    num_posts = 10
    query = request.args.get('q', '')
    results = PACKTPUB.query.search(query, limit=num_posts)
    # <-- this won't work because you can't marshal SQLAlchemy models
    return 'ok'


@app.route('/packtpubs/create', methods=['POST'])
def packtpubs_create():
    j = request.get_json()

    packtpub = PACKTPUB(
        title=request.get_json().get('title'),
        isbn=request.get_json().get('isbn')
    )
    db.session.add(packtpub)
    db.session.commit()
    return 'DONE'


@app.before_first_request
def bootstrap():
    db.create_all()  # <- create the necessary table


if __name__ == "__main__":
    db.init_app(app)  # <- lazy bind the database to the app
    app.run()

```

**Comment by azeznassar** [comment]
I'm also getting `AttributeError: 'BaseQuery' object has no attribute 'search'` with a use case very similar to the docs. Is this still working?

**Comment by skrypnyk-dmytro** [comment]
same error

**Comment by ghost** [comment]
Getting the same error. Have recreated the tables. Also not seeing any whoosh_index folder either. Any suggestions?

**Comment by chaytonchen** [comment]
Getting the same error. There is no steps to init app here. I use the method search_index(app, model) and create index successfully. But still get the same error.

**Comment by blakev** [comment]
Fixed #1 in version 0.1.2 on pypi

**Comment by thezoug** [comment]
Hate to reopen a closed ticket, but it appears that this error still occurs in the latest version...

**Comment by ethanshealey** [comment]
Am also having this same issue

**Comment by PoomSombutboon** [comment]
still have this issue
